[project]
name = "prompt-to-comic-frontend"
version = "0.1.0"
description = "Frontend for Prompt-to-Comic app"
requires-python = ">=3.11"
dependencies = [
    "streamlit",
    "httpx",
    "python-dotenv",
    "requests>=2.32.4",
] 
